Fix paths in testapp
Adding `testapp` to the workspaces seemed to break the testapp, with the error:

```
 Error: template not found: template.njk
 ```

I think this is caused by the template path no longer being relative.

Removing the tesapp from the workspace seems to fix it.